apiVersion: v1
kind: Template
metadata:
  name: integreatly-operator
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: integreatly-operator

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: integreatly-operator
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: integreatly-operator
      template:
        metadata:
          labels:
            name: integreatly-operator
        spec:
          serviceAccountName: integreatly-operator
          containers:
            - name: integreatly-operator
              # Replace this with the built image name
              image: quay.io/integreatly/integreatly-operator:latest
              command:
                - integreatly-operator
              imagePullPolicy: Always
              env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "integreatly-operator"
                - name: CLUSTER_HAS_OLM
                  value: ${CLUSTER_HAS_OLM}
                - name: INSTALLATION_CONFIG_MAP
                  value: ${INSTALLATION_CONFIG_MAP}

  - apiVersion: authorization.openshift.io/v1
    kind: ClusterRole
    metadata:
      name: integreatly-operator
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - list
          - create
          - watch
      - apiGroups:
          - kafka.strimzi.io
        resources:
          - kafkas
        verbs:
          - get
          - create
      - apiGroups:
          - operators.coreos.com
        resources:
          - subscriptions
          - operatorgroups
          - catalogsourceconfigs
        verbs:
          - list
          - create
          - watch

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: integreatly-operator
    subjects:
      - kind: ServiceAccount
        name: integreatly-operator
        namespace: ${NAMESPACE}
    roleRef:
      kind: ClusterRole
      name: integreatly-operator
      apiGroup: rbac.authorization.k8s.io

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: integreatly-operator
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
        verbs:
          - '*'
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - get
      - apiGroups:
          - apps
        resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
        verbs:
          - '*'
      - apiGroups:
          - monitoring.coreos.com
        resources:
          - servicemonitors
        verbs:
          - get
          - create
      - apiGroups:
          - apps
        resourceNames:
          - integreatly-operator
        resources:
          - deployments/finalizers
        verbs:
          - update
      - apiGroups:
          - aerogear.org
        resources:
          - '*'
        verbs:
          - '*'

  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: integreatly-operator
    subjects:
      - kind: ServiceAccount
        name: integreatly-operator
    roleRef:
      kind: Role
      name: integreatly-operator
      apiGroup: rbac.authorization.k8s.io

parameters:
  - name: NAMESPACE
    description: Namespace of the project that is being deployed to
    value: "openshift-integreatly-operator"

  - name: CLUSTER_HAS_OLM
    description: Defines whether the cluster integreatly operator is being deployed to has OLM installed.
    value: "true"

  - name: INSTALLATION_CONFIG_MAP
    description: Name of a config map which stores configuration for each product being installed.
    value: "integreatly-config"